### ISSUE TITLE
error: "Slope along x is too large" for i_case 84

### ISSUE THREAD

**Issue by nbasse** [LHEEA/HOS-ocean#18]
Trying to run with case 84 and input settings:

`Restart previous computation :: i_restart        :: 0`
`Choice of computed case      :: i_case           :: 84`
`--- Geometry of the horizontal domain`
`Length in x-direction        :: xlen             :: 16.0000000000000000e+00`
`Length in y-direction        :: ylen             :: 1.0`
`--- Time stuff`
`Duration of the simulation   :: T_stop           :: 1.0000000000000000e+01`
`Sampling frequency (output)  :: f_out            :: 5.0000000000000000e+01`
`Tolerance of RK scheme       :: toler            :: 1.0e-7`
`Dommermuth initialisation    :: n                :: 4`
`Dommermuth initialisation    :: Ta               :: 10.0`
`--- Physical dimensional parameters`
`Gravity                      :: grav             :: 9.82`
`Water depth                  :: depth            :: -1.`

Gives this error:

`CPU time for Output time step   0.08    5    4    10.783     0.500     0.097`
`*****************          58  % *****************    `                                                                 
`Slope along x is too large...  3.379E+01   9.558E+02    `                                                                
`Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO                     STOP 1`

What is the cause for this error?
I have encountered it a few times before for other cases with manual inputs.
But then I have managed to get past the error by changing the inputs slightly.

For case 84 I can't find any combination that works.

(The end goal for me is to simulate some nonlinear waves that I can use to test my own functions)

Thanks in advance for any possible help!

**Comment by gducrozet** [comment]
The case you try to simulate (case 84) corresponds to a very steep wave (ka=0.40).

What you observe is a numerical instability associated to the choice of the numerical parameters. Since the wave you want to simulate is close to breaking, those numerical parameters need to be chosen wisely to prevent from having such behavior (since in the model there is no numerical treatment to smooth the surface and artificially prevent the development of such instabilities).

Then, you can change the values of n1, p1 and M in `variables_3D.f90` to coherent value to overcome this problem. You may refer to [https://doi.org/10.1142/9789812836502_0004](url) Table 5 for coherent choices of parameters that should allow a correct wave propagation.

Best,

Guillaume

**Comment by nbasse** [comment]
Thank you for your answer!

> since in the model there is no numerical treatment to smooth the surface and artificially prevent the development of such instabilities

Ok, then I understand.

How come this error some times occur even for very flat waves?

Do you have any recommendations on combinations of parameters to aim for or to avoid when using moderately steep waves?

Best Regards,
Niclas

**Comment by gducrozet** [comment]
> How come this error some times occur even for very flat waves?

I think it may appear if the choice of numerical parameters is not adapted at all (if you use a too refined discretization and a non-linear order not coherent with this choise). After, I do not know what you call 'very flat wave' and/or if you have examples.

> Do you have any recommendations on combinations of parameters to aim for or to avoid when using moderately steep waves?

For regular waves, the best is to use an order of non-linearity consistent with the number of points chosen. Namely, if you use n1 points on one wavelength, the highest mode solved is n1/2. If you want to solve accurately this mode (including all nonlinearities), you need to set-up M=n1/2 so that this n1/2 harmonics is correctly solved. Typical example (solving one wavelength) : n1=16, M=8

For irregular waves, you can make similar rule of thumb based on the peak of the spectrum.

**Comment by nbasse** [comment]
Ok!
I will try to increase M then and hope it solves some of these problems.
Thank you!
