### ISSUE TITLE
Breaking limit and adaptive time-step

### ISSUE THREAD

**Issue by dh810** [LHEEA/HOS-ocean#9]
Having gone through the literature and the source code, I have  a couple of questions relating to the above:
1. With regards to the breaking (or steepness) limit:
On `line 539` of `HOS-ocean.f90`, there is a check on the maximum slope of the surface and the simulation stops when the maximum absolute value of `etax` and `etay` exceed a threshold value of 10.0. I wasn't able to find what `etax` and `etay` correspond to, but I am assuming they correspond to
![image](https://user-images.githubusercontent.com/9944506/36421573-e4dbcba2-1630-11e8-896e-0817559f05fa.png)
 respectively. Aside from this though, what does the threshold value of 10.0 correspond to? Is it based on theoretical arguments similar to the arguments made [here](https://www.sciencedirect.com/science/article/pii/S0029801817303748)?

2. With regards to the adaptive time-step:
I am unsure about the conditions on which the time-step is adapted. Is it adapted to conserve energy or is it to minimise errors in some other way? Most of the literature simply states that "The two surface quantities are then marched in time using an efficient 4th-order Runge-Kutta scheme featuring an adaptive step-size control and in which the linear part of the equations is integrated analytically."

Thank you.

**Comment by gducrozet** [comment]
@dh810 some elements regarding your questions:

1. `etax` and `etay` indeed correspond to, ![image](https://user-images.githubusercontent.com/9944506/36421573-e4dbcba2-1630-11e8-896e-0817559f05fa.png) respectively. The threshold value of 10.0 is not based on a theoretical argument, except the fact that when the local slope is at such high values, the simulation exhibits numerical instabilities (this is not a realistic value of the local slope). It was just a criteria used to detect the appearance of those instabilities and not a breaking onset parameter. For this, I can advise two recent papers:

> Betsy Seiffert, Guillaume Ducrozet, Félicien Bonnefoy. Simulation of breaking waves using the High-Order Spectral method with laboratory experiments: Wave-breaking onset. Ocean Modelling, Volume 119, Pages 94-104, 2017, [10.1016/j.ocemod.2017.09.00](https://www.sciencedirect.com/science/article/pii/S1463500317301427?via%3Dihub)

> Betsy Seiffert, Guillaume Ducrozet. Simulation of breaking waves using the high-order spectral method with laboratory experiments: wave-breaking energy dissipation. Ocean Dynamics, Volume 68, Issue 1, pp 65–89, 2018, [10.1007/s10236-017-1119-3](https://link.springer.com/article/10.1007%2Fs10236-017-1119-3)

2. The time-step is always adapted in order to satisfy a criteria on the accuracy of the time integration itself. This is quite classical and usually refered as Runge-Kutta Cash-Karp scheme. The corresponding reference is the following:

> J. R. Cash and A. H. Karp. A variable order Runge-Kutta method for initial value
problems with rapidly varying right-hand sides. ACMTrans.Math. Softw., 16(3):201–
222, 1990.

Hope this helps!

Guillaume.
